apiVersion: v1
kind: Namespace
metadata:
  name: kafka-ns
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-hs
  namespace: kafka-ns
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: kafka
  ports:
    - name: kafka
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: controller
      protocol: TCP
      port: 9093
      targetPort: 9093
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-cm
  namespace: kafka-ns
data:
  CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk" # Generated once: kafka-storage.sh random-uuid
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-ss
  namespace: kafka-ns
spec:
  serviceName: "kafka-hs"
  replicas: 3
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: apache/kafka:latest
          ports:
            - containerPort: 9092
              name: kafka
            - containerPort: 9093
              name: controller
          env:
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:9093"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://$(POD_NAME).kafka-hs.kafka-ns.svc.cluster.local:9092"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "0@kafka-ss-0.kafka-hs.kafka-ns.svc.cluster.local:9093,1@kafka-ss-1.kafka-hs.kafka-ns.svc.cluster.local:9093,2@kafka-ss-2.kafka-hs.kafka-ns.svc.cluster.local:9093"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "3"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "3"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "2"
            - name: KAFKA_LOG_DIRS
              value: "/var/lib/kafka/data"
            - name: KAFKA_CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: kafka-cm
                  key: CLUSTER_ID
            - name: KAFKA_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data
          command:
            - bash
            - -c
            - |
              export KAFKA_NODE_ID=${HOSTNAME##*-}

              # Format storage if not already formatted
              /opt/kafka/bin/kafka-storage.sh format -t ${KAFKA_CLUSTER_ID} -c /opt/kafka/config/kraft/server.properties || true

              # Start Kafka
              exec /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/kraft/server.properties
      resources:
        requests:
          cpu: "128m"
          memory: "512Mi"
        limits:
          cpu: "1"
          memory: "1Gi"
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
