apiVersion: v1
kind: Namespace
metadata:
  name: postgres-ns
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgres-ns
type: Opaque
stringData:
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  POSTGRES_DB: cloud_service_db
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-cm
  namespace: postgres-ns
data:
  postgresql.conf: |
    # ... content of your postgresql.conf ...
    listen_addresses = '*'
  pg_hba.conf: |
    # ... content of your pg_hba.conf ...
    host    all             all             0.0.0.0/0               md5
  postgres-entrypoint.sh: |
    #!/bin/bash
    # ... content of your script ...
    exec postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-hs
  namespace: postgres-ns
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - name: tcp
      protocol: TCP
      port: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: postgres-ns
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: postgres-ns
spec:
  replicas: 1
  serviceName: "postgres-hs"
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:bookworm
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-cm-files
              mountPath: /docker-entrypoint-initdb.d/
            - name: postgres-conf
              mountPath: /etc/postgresql/
      volumes:
        - name: postgres-cm-files
          configMap:
            name: postgres-cm
            items:
              - key: postgres-entrypoint.sh
                path: init.sh
            defaultMode: 0755
        - name: postgres-conf
          configMap:
            name: postgres-cm
            items:
              - key: postgresql.conf
                path: postgresql.conf
              - key: pg_hba.conf
                path: pg_hba.conf
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 1Gi
