apiVersion: v1
kind: Namespace
metadata:
  name: rabbitmq-ns
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: rabbitmq-ns
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: guest
---
#    kubectl create configmap rabbitmq-config -n rabbitmq-ns \
#      --from-file=rabbitmq.conf=deploy/configurations/rabbitmq/rabbitmq.local.conf
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: rabbitmq-ns
data:
  rabbitmq.conf: |
    # ... content of your rabbitmq.local.conf ...
    loopback_users.guest = false
---
# The "Headless" Service
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-hs
  namespace: rabbitmq-ns
spec:
  clusterIP: None
  selector:
    app: rabbitmq
  ports:
    - port: 5672
      name: amqp
    - port: 15672
      name: http-mgmt
---
# The "ClusterIP" Service for your apps
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: rabbitmq-ns
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: http
      port: 15672
      targetPort: 15672
---
# The StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: rabbitmq-ns
spec:
  replicas: 1
  serviceName: "rabbitmq-hs"
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:management-alpine
          ports:
            - containerPort: 5672 # amqp
            - containerPort: 15672 # http management
          envFrom:
            - secretRef:
                name: rabbitmq-secret
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
            - name: rabbitmq-conf
              mountPath: /etc/rabbitmq/
      volumes:
        - name: rabbitmq-conf
          configMap:
            name: rabbitmq-config
            items:
              - key: rabbitmq.conf
                path: rabbitmq.conf

  # Template for the persistent volume
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
