apiVersion: v1
kind: Namespace
metadata:
  name: redis-ns
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: redis-ns
data:
  redis.conf: |
    # ... content of your redis-stack.local.conf ...
    # Make sure persistence is enabled!
    save 60 1
    appendonly yes
---
apiVersion: v1
kind: Service
metadata:
  name: redis-hs
  namespace: redis-ns
spec:
  clusterIP: None
  selector:
    app: redis
  ports:
    - port: 6379
      name: tcp-redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: redis-ns
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: redis-ns
spec:
  replicas: 1
  serviceName: "redis-hs"
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis/redis-stack-server:latest
          args: ["/conf/redis.conf"]
          ports:
            - containerPort: 6379
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: redis-conf
              mountPath: /conf
              readOnly: true
      volumes:
        - name: redis-conf
          configMap:
            name: redis-config
            items:
              - key: redis.conf
                path: redis.conf

  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 1Gi
