apiVersion: v1
kind: Namespace
metadata:
  name: redis-ns
---
#    kubectl create configmap redis-config -n redis-ns \
#      --from-file=redis.conf=deploy/configurations/redis-stack/redis-stack.local.conf
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: redis-ns
data:
  redis.conf: |
    # ... content of your redis-stack.local.conf ...
    # Make sure persistence is enabled!
    save 60 1
    appendonly yes
---
# The "Headless" Service for the StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: redis-hs
  namespace: redis-ns
spec:
  clusterIP: None
  selector:
    app: redis
  ports:
    - port: 6379
      name: tcp-redis
---
# The "ClusterIP" Service for your apps
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: redis-ns
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
---
# The StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: redis-ns
spec:
  replicas: 1
  serviceName: "redis-hs"
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis/redis-stack-server:latest
          # Tell redis to use our mounted config file
          args: ["/conf/redis.conf"]
          ports:
            - containerPort: 6379
          volumeMounts:
            # Mount for persistence
            - name: redis-data
              mountPath: /data
            # Mount for config
            - name: redis-conf
              mountPath: /conf
      volumes:
        - name: redis-conf
          configMap:
            name: redis-config
            items:
              - key: redis.conf
                path: redis.conf

  # This template creates the PVC for pod 'redis-0'
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
