apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: kube-system
data:
  traefik.yaml: |
    entryPoints:
      web:
        address: :80
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
      websecure:
        address: :443
        http:
          tls:
            certResolver: letsencrypt

    certificatesResolvers:
      letsencrypt:
        acme:
          email: your-email@pinespot.uz
          storage: /data/acme.json
          httpChallenge:
            entryPoint: web
