[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
rustls.workspace = true
tokio.workspace = true
axum.workspace = true
axum-core.workspace = true
axum-extra.workspace = true
chrono.workspace = true
lapin.workspace = true
rand.workspace = true
redis.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
sqlx-core.workspace = true
tower.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
validator.workspace = true
rustls-pemfile.workspace = true
tokio-rustls.workspace = true
reqwest.workspace = true
tonic.workspace = true
rdkafka.workspace = true
kube = { version = "2.0.1", features = ["runtime", "derive"] }
bcrypt = "0.17.1"
url = { version = "2.5.7", features = ["serde"] }
thiserror = "2.0.16"
jsonwebtoken = "9.3.1"
object_store = { version = "0.12.4", features = ["gcp", "aws"] }
oauth2 = "5.0.0"
